name: check glossary terms in latex source files

on:
  push:
    branches-ignore:
      - main
      - sources

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: run script (see output, expand below)
        if: ${{ github.event_name == 'push' }}
        run: |
           python3 .github/workflows/scripts/check_glossary.py
