name: Build LaTeX document
on:
  workflow_dispatch:
  #schedule:      
  #  - cron: '0 0 * * *'
  push:
    branches:
      - sources
    paths:
      - 'documents/**'
  
permissions:                  
  contents: write             
  pull-requests: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: checkout the builds repo
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
          token: ${{secrets.NAN1FY_ACTION_COMPILE}}
      - name: move main to runner.temp
        run: |
          mv main "${RUNNER_TEMP}"
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          separator: ","
          files: |
            documents/**/*.tex
            documents/*/interni/glossario.csv
      - name: delete ignored and unchanged latex documents
        run: |
          shopt -s globstar
          ls documents/**/*.tex > .all
          echo ${{ steps.changed-files.outputs.all_changed_files }} | tr "," "\n" | sort > .changed
          sed -i 's/glossario.csv/glossario.tex/g' .changed
          cat .changed
          comm -23 .all .changed >> .latexignore
          while IFS= read -r f; do rm -rf "${f}"; done < .latexignore
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "**/!(*template*)/*.tex"
          working_directory: documents/
          work_in_root_file_dir: true
          docker_image: ghcr.io/xu-cheng/texlive-full:latest
          pre_compile: |
            tlmgr option repository ctan
            tlmgr update --self --all
            tlmgr install subfiles cbfonts-fd lipsum footmisc csquotes plex fontaxes mathabx textgreek makecell wrapfig siunitx adjustbox floatflt capt-of varwidth datatool xstring csvsimple ragged2e adjustbox threeparttable pgf pgfopts datetime2 enumitem xurl
      - name: set timestamp and version for builds of changed files and replace the old ones in the local copy of `main`
        run: |
          shopt -s globstar
          shopt -s extglob
          for f in documents/**/!(*template*)/*.tex; do
            [[ ! -f "$f" ]] && continue
            filename=$(basename -- "$f")
            # escludo i verbali firmati dalla compilazione
            if [[ "$filename" != "VE_2024_03_12.tex" && "$filename" != "VE_2024_03_12_II.tex" ]]; then
              rm -f "${RUNNER_TEMP}/main/${f%.tex}"*
              sudo touch -amd "$( date -R -r "$f" )" "${f%.tex}.pdf"
              version=$(grep "^\s*% changelog:" "$f" | cut -d '"' -f2 | cut -d ',' -f1 | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
              [[ ! -z "$version" ]] && mv "${f%.tex}.pdf" "${f%.tex}_v${version}.pdf" && f="${f%.tex}_v${version}.tex"
              rsync -aR "${f%.tex}.pdf" "${RUNNER_TEMP}/main"
            fi
          done
      - name: push to builds repo
        run: |
          pushd "${RUNNER_TEMP}/main"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Automatic LaTeX compilation $(date +%Y-%m-%d)" \
            -m "Triggered by ${{ github.actor }} pushing changes to the source branch at $(date +%H:%M:%S)." \
            || continue
          git push
          git push
        env:
          TZ: Europe/Rome
