name: release documents
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  releases:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v2
      - name: create release with tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          pushd "documents/${GITHUB_REF_NAME}" 
          zip -r "${GITHUB_REF_NAME}.zip" .
          popd
          mv "documents/${GITHUB_REF_NAME}/${GITHUB_REF_NAME}.zip" .
          gh release create "$GITHUB_REF_NAME" -t "$GITHUB_REF_NAME" "${GITHUB_REF_NAME}.zip" -n "Documentazione relativa alla milestone **${GITHUB_REF_NAME}**." 
        env:
          GITHUB_TOKEN: ${{ github.token }}
